### ISSUE TITLE
Launching Error

### ISSUE THREAD

**Issue by PersonGuy46** [magistermaks/mod-stylishoccult#5]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 16 with version 17 or later.
Unmet dependency listing:
	 - Mod 'Stylish Occult' (stylish_occult) 0.10.0 requires version 17 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 16!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by magistermaks** [comment]
Ooops! sorry for that, fixed in 0.10.1 
Thanks for the report :+1:
